### ISSUE TITLE
Linter not running on macOX

### ISSUE THREAD

**Issue by bratelefant** [leaonline/oauth2-server#17]
**Describe the bug**
I do not get the linter to run on macOS.

**To Reproduce**
1. Install test-proxy according to the contribution guidelines.
2. Run `meteor npm run lint`

**Expected behavior**
Lint script should run without errors.

**Logs**
```

> test-proxy@ lint /folder/oauth2-server/test-proxy
> standardx -v ./packages/oauth2-server | snazzy

internal/modules/cjs/loader.js:936
  throw err;
  ^

Error: Cannot find module './lib/_stream_readable.js'
Require stack:
- /folder/oauth2-server/test-proxy/node_modules/readable-stream/readable.js
- /folder/oauth2-server/test-proxy/node_modules/snazzy/index.js
- /folder/oauth2-server/test-proxy/node_modules/snazzy/bin/cmd.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:933:15)
    at Function.Module._load (internal/modules/cjs/loader.js:776:27)
    at Module.require (internal/modules/cjs/loader.js:1005:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/folder/oauth2-server/test-proxy/node_modules/readable-stream/readable.js:7:30)
    at Module._compile (internal/modules/cjs/loader.js:1116:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1145:10)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Function.Module._load (internal/modules/cjs/loader.js:821:12)
    at Module.require (internal/modules/cjs/loader.js:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/folder/oauth2-server/test-proxy/node_modules/readable-stream/readable.js',
    '/folder/oauth2-server/test-proxy/node_modules/snazzy/index.js',
    '/folder/oauth2-server/test-proxy/node_modules/snazzy/bin/cmd.js'
  ]
}
standardx: Unexpected linter output:

Error: Failed to load plugin 'react' declared in 'BaseConfig » eslint-config-standard-jsx': Cannot find module 'es-errors'
Require stack:
- /folder/oauth2-server/test-proxy/node_modules/get-intrinsic/index.js
- /folder/oauth2-server/test-proxy/node_modules/call-bind/index.js
- /folder/oauth2-server/test-proxy/node_modules/object.fromentries/index.js
- /folder/oauth2-server/test-proxy/node_modules/eslint-plugin-react/index.js
- /folder/oauth2-server/test-proxy/node_modules/@eslint/eslintrc/lib/config-array-factory.js
- /folder/oauth2-server/test-proxy/node_modules/@eslint/eslintrc/lib/index.js
- /folder/oauth2-server/test-proxy/node_modules/eslint/lib/cli-engine/cli-engine.js
- /folder/oauth2-server/test-proxy/node_modules/eslint/lib/cli-engine/index.js
- /folder/oauth2-server/test-proxy/node_modules/eslint/lib/api.js
- /folder/oauth2-server/test-proxy/node_modules/standard/options.js
- /folder/oauth2-server/test-proxy/node_modules/standardx/options.js
- /folder/oauth2-server/test-proxy/node_modules/standardx/bin/cmd.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:933:15)
    at Function.Module._load (internal/modules/cjs/loader.js:776:27)
    at Module.require (internal/modules/cjs/loader.js:1005:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/folder/oauth2-server/test-proxy/node_modules/get-intrinsic/index.js:5:14)
    at Module._compile (internal/modules/cjs/loader.js:1116:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1145:10)
    at Module.load (internal/modules/cjs/loader.js:981:32)
    at Function.Module._load (internal/modules/cjs/loader.js:821:12)
    at Module.require (internal/modules/cjs/loader.js:1005:19)

If you think this is a bug in `standardx`, open an issue: https://github.com/standard/standardx/issues
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test-proxy@ lint: `standardx -v ./packages/oauth2-server | snazzy`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the test-proxy@ lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.3

**Comment by jankapunkt** [comment]
woa, why is there a react dependency :eyes:

**Comment by jankapunkt** [comment]
I fixed this on `master`, please take a look at it.

```shell
git pull --ff
cd test-proxy
rm -rf node_modules
meteor reset
meteor npm install
meteor npm run setup
meteor npm run lint
````

**Comment by bratelefant** [comment]
Working fine, thanks a lot!
